app/core/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    ArtistListView,
    ArtistDetailView,
)
urlpatterns = [
    path('artists/', ArtistListView.as_view(), name='artist.list'),
    path('artist/<int:pk>/', ArtistDetailView.as_view(), name='artist.read'),
]

app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('app.core.urls'))
]

app/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Artist(models.Model):
    name = models.CharField(max_length=30)


class Album(models.Model):
    name = models.CharField(max_length=30)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)


class Song(models.Model):
    title = models.CharField(max_length=30)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)


class User(AbstractUser):
    REQUIRED_FIELDS = ('first_name', )

    first_name = models.CharField(max_length=150, blank=False)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.full_name

    @property
    def full_name(self):
        if not self.last_name:
            return self.first_name
        return '{} {}'.format(self.first_name, self.last_name)

app/core/views.py
from django.views.generic import (
    DetailView,
    ListView,
)
from .models import Artist


class ArtistListView(ListView):
    model = Artist
    context_object_name = 'artist_list'


class ArtistDetailView(DetailView):
    model = Artist

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['foo'] = 'bar'
        return context

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello Django</title>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
{% block body %}
{% endblock body %}
</body>
</html>

app/templates/core/artist_detail.html
{% extends 'base.html' %}

{% block body %}
    <h1 class="mb-4 text-2xl">{{ artist.name }}</h1>

    <ul class="ml-6 list-disc">
    {% for album in artist.album_set.all %}
        <li>{{ album.name }}</li>
    {% endfor %}
    </ul>
{% endblock %}

app/templates/core/artist_list.html
{% extends 'base.html' %}

{% block body %}
    <ul class="ml-6 list-disc">
    {% for artist in artist_list %}
        <li>{{ artist.name }}</li>
    {% endfor %}
    </ul>
{% endblock %}